http_server:
  host: "0.0.0.0"
  port: ":8080"

cache:
  size: 3
  capacity: 10

database:
  host: "postgres"
  port: "5432"
  user: "admin"
  password: "admin1234"
  name: "orders_db"
  sslmode: "disable"

producer:
  nmb_of_orders: 3

kafka:
  brokers:
    - "kafka:9092"
  topic: "order_topic"
  group_id: "order_group"

